### ISSUE TITLE
complie error 

### ISSUE THREAD

**Issue by YouarexD-de** [dufernst/LegionCore-7.3.5#7]
Hello together

i get this error when i try to complie the core
i complied it with vs 2017 and boost 1.66.0 

https://gyazo.com/e20f240a74054c5737dfc59b2b44982e

https://gyazo.com/43dea69ba3f67ef54a684a64fc402968

https://gist.github.com/YouarexD-de/a898e8e820262837a5a87178a83c07ad

**Comment by Ramys** [comment]
Here..
https://github.com/dufernst/LegionCore-7.3.5/issues/6#issuecomment-706737086

**Comment by YouarexD-de** [comment]
problem is fixed with the version of 1.64.0

**Comment by artemis257** [comment]
does it matter what version of CMake is used? 

I'm currently running vs 2017 and boost 1.66.0 but still get the same error as above.  using CMake 3.17.5

**Comment by Ramys** [comment]
Boost 1.64 guy.

**Comment by artemis257** [comment]
running 1.64
Cmake 3.18.3 (not RC)
vs 2017 community
screenshot is of the output. maybe I have something configured wrong, as it can't find boost?
![boost](https://user-images.githubusercontent.com/1930351/97928778-b578d800-1d35-11eb-98a3-701b2f5b2643.jpg)

**Comment by dufernst** [comment]
@artemis257 set BOOST_ROOT to your boost directory and rerun cmake generate.

**Comment by artemis257** [comment]
did that, it compiled and generated. went to move on to the next step of building it in VS 2017 and got the following errors on completion. suggestions?

![image](https://user-images.githubusercontent.com/1930351/97934704-6be3b980-1d44-11eb-9d28-3b8d1ad42b1d.png)

**Comment by dufernst** [comment]
@artemis257 can you confirm that you actually have those files and that your cmake variables are referencing them correctly?

**Comment by dufernst** [comment]
Closing because of the absence of a response, if anyone else has any problems, please open a new issue.
